version: '3'

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        network_mode: host
        ports:
            - "9090:9090"
        volumes:
            - "./prometheus.yml:/etc/prometheus/prometheus.yml"

    grafana:
        image: grafana/grafana
        container_name: grafana
        network_mode: host
        ports: 
            - "3000:3000"

    quarkus:
        build: 
            dockerfile: cotacao/src/main/docker/Dockerfile.jvm
            context: .
        image: quarkus
        container_name: quarkus
        ports: 
            - "8080:8080"
        depends_on: 
            - postgres    
    
    postgres:
        image: postgres
        network_mode: host
        environment: 
            - POSTGRES_DB=cotacao
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - "5432:5432"